### ISSUE TITLE
commit 989d7d831ba5af40ca95b0afd80f34dc862b0bc5 breaks faldo.ttl

### ISSUE THREAD

**Issue by nlwashington** [JervenBolleman/FALDO#25]
on line https://github.com/JervenBolleman/FALDO/blob/master/faldo.ttl#L254
it ends with "." before the end of file.  L254 and L255 should be reversed.

https://github.com/JervenBolleman/FALDO/commit/989d7d831ba5af40ca95b0afd80f34dc862b0bc5#diff-fcc2583d7eb17a7c7734852a84ff2828R255

**Comment by indiedotkim** [comment]
@nlwashington Please verify that commit [https://github.com/JervenBolleman/FALDO/commit/b374144296920de73bb52d1d29c7a84c404aa709] fixes the issue.

**Comment by JervenBolleman** [comment]
@nlwashington sorry for breaking your pipeline. My fault, should have waited with pushing until I had time to test today.
@indiedotkim thank you for patching so quick!

**Comment by nlwashington** [comment]
all is good!
