### ISSUE TITLE
0-based/1-based coordinate system 

### ISSUE THREAD

**Issue by Kleurenprinter** [JervenBolleman/FALDO#29]
File formats containing genome information can use both 0-based (e.g. BED/BAM) as 1-based (e.g. VCF/GFF/SAM). FALDO documentation does not specify to be using either system, nor is there an ontology included to specify which coordinate system given coordinates are using.

Expanding on this makes it possible to use the FALDO ontologies for the conversion of a broader array of file formats without introducing problems.

**Comment by indiedotkim** [comment]
Positions are 1-based. From the description of the `position` datatype:

> Denoted in 1-based closed coordinates, i.e. the position on the first amino acid or nucleotide of a sequence has the value 1. For nucleotide sequences we count from the 5'end of the sequence, while for Aminoacid sequences we start counting from the N-Terminus.
